package com.example.packagemanager.services

import com.example.packagemanager.database.DataBase
import com.example.packagemanager.model.User

object UserService {

    private var idAutogenerated: Int = 0
    private var loggedUser: User? = null

    fun saveUser(name: String, password: String, isAdmin: Boolean, storehouseId: Int) {
        idAutogenerated++
        val newUser = User(idAutogenerated, name, password, isAdmin, storehouseId)
        DataBase.saveUser(newUser)
    }

    fun logIn(name: String, password: String): Boolean {
        if ((name == "") || (password == ""))
            return false

        loggedUser = DataBase.findUserByNameAndPassword(name, password)
        return loggedUser != null
    }

    fun logOut() {
        loggedUser = null
    }

    fun getLoggedUser(): User? {
        return loggedUser
    }
}